name: ClearML Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - 'MyLocalModel.py'  # Specify the path to your code files

jobs:
  run_clearml_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'
      
      - name: Install dependencies
        run: |
          pip install clearml

      - name: Run ClearML Pipeline
        env:
          CLEARML_API_KEY: PSLFJV7QS183E1W2EELD
        run: |
          python MyLocalModel.py
