name: ClearML CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set your branch here

jobs:
  MLOps_Project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install ClearML
        run: pip install clearml

      - name: Create environment file for ClearML configuration
        run: echo "CLEARML_CONFIG_FILE=clearml.conf" >> $GITHUB_ENV

      - name: Initialize ClearML
        run: clearml-init
        env:
          CLEARML_CONFIG_FILE: ${{ env.CLEARML_CONFIG_FILE }}

      - name: Install TensorFlow
        run: pip install tensorflow

      - name: Install NumPy
        run: pip install numpy

      - name: Submit pipeline for remote execution
        run: clearml-pipe submit --queue default --name "MLOps Pipeline"    

      - name: Run Python file
        run: python MyLocalModel.py

  
