name: ClearML CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set your branch here

jobs:
  MLOps_Project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install ClearML
        run: pip install clearml

      - name: Set ClearML configuration file
        run: echo "::set-env name=CLEARML_CONFIG_FILE::clearml.conf"

      - name: Initialize ClearML
        run: clearml-init

      - name: Run Python file
        run: python MyLocalModel.py
