name: Train on Push

on: [push]

jobs:

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'  # Replace with your Python version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ClearML task
        run: python MyLocalModel.py  # Replace with your file's name
        env:
          # Add ClearML API key environment variable
          CLEARML_API_KEY: PSLFJV7QS183E1W2EELD
