name: ClearML CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set your branch here

jobs:
  task-stats-to-comment:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
    runs-on: ubuntu-20.04
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install ClearML
        run: pip install clearml

      - name: Start the task
        id: launch_task
        run: |
          python MyLocalModel.py
