name: ClearML Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'MyLocalModel.py'  # Path to your Python script

jobs:
  run_clearml_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install clearml
          pip install tensorflow  # Install TensorFlow

      - name: List installed packages
        run: |
          pip list

      - name: Run ClearML pipeline
        env:
          CLEARML_API_HOST: 'https://api.community.clear.ml'
          CLEARML_API_KEY: 'PSLFJV7QS183E1W2EELD'
        run: |
          python MyLocalModel.py  # Run your script
